# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - rm -rf build/

script: ./script/test -vv

# setting sudo to 'false' allows running on travis-ci new infra (docker)
sudo: false
